on:
  push:
    branches: [ main ]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: manojsinghceh/owasp-vulnerableapp-php:latest
          jobs:
  Docker push:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Setting up app locally
    - name: Set up local image
      continue-on-error: true
      run: |
        docker pull ghcr.io/devopscicd17/vulnerableapp-php:main
        docker image ls
	docker container run ghcr.io/devopscicd17/vulnerableapp-php:main
